name: Horta Modular
description: ""
featimg: horta-capa.jpg

url: http://hortamodular.com
baseurl: ''
port: 4545
permalink: /:title/

media_folder: /media
destination: jekyllbuild
full_rebuild: true
gems: [jekyll-paginate]
paginate: 8
paginate_path: /page/:num/
infinite_scroll: true #false for pagination

tumblr: ""
pinterest: ""
instagram: "https://www.instagram.com/hortamodular/"
twitter: ""
facebook: ""
youtube: ""
vimeo: ""
soundcloud: ""
email: "hortamodular@gmail.com"

encoding: utf-8

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      type: "standard"
      homedisplay: "featimg"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      type: "standard"
      homedisplay: "featimg"

# prose.io
prose:
  media: 'media'
  ignore:
    - .gitignore
    - _config.yml
    - _layouts
    - _includes
    - _sass
    - css
    - fonts
    - js
    - LICENCE
    - CNAME
    - README.md
    - index.html
    - media/favicons
  metadata:
    _pages:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "homedisplay"
        field:
          element: "hidden"
          value: "featimg"
      - name: "title"
        field:
          element: "text"
          label: "nome da página"
      - name: "permalink"
        field:
          element: "text"
          label: "escolha um url para essa página"
          placeholder: "/url-da-pagina/"
      - name: "nav-title"
        field:
          element: "text"
          label: "nome da página para o menu (deixar em branco se não quiser no menu)"
      - name: "description"
        field:
          element: "textarea"
          label: "descrição curta da página (deixar em branco se não quiser que página apareça na home)"
      - name: "cover-image"
        field:
          element: "text"
          label: "imagem de capa para a página (tem que ser .jpg por enquanto)"
          placeholder: "horta2.jpg"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
relative_permalinks: false
include: ['_pages']
exclude: [.git, .gitignore, .sass-cache, README.md, jekyllbuild]
